/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BakeryManagementSystem;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author xeetr
 */
public class Addemployee extends javax.swing.JFrame {
   

    /**
     * Creates new form Addemployee
     */
    public Addemployee(String id) {
        initComponents();
     setLocationRelativeTo(null);
        setResizable(false);
        connect();
//        loadtable();
        
    }

    Connection conn;
    PreparedStatement pst;
    Statement st;
    
    public void connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/Bakerymanagementsystem", "root", "");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ctz = new javax.swing.JTextField();
        egender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eadd = new javax.swing.JTextField();
        ephone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        euser = new javax.swing.JTextField();
        epass = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        epos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        esal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 6, 37, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 30, 30);

        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        jPanel1.add(ename);
        ename.setBounds(70, 120, 220, 30);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 100, 50, 16);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Citizen Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 170, 130, 16);

        ctz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctzActionPerformed(evt);
            }
        });
        jPanel1.add(ctz);
        ctz.setBounds(70, 190, 220, 30);

        egender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egenderActionPerformed(evt);
            }
        });
        jPanel1.add(egender);
        egender.setBounds(70, 270, 220, 30);

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 240, 90, 30);

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 390, 90, 16);

        eadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaddActionPerformed(evt);
            }
        });
        jPanel1.add(eadd);
        eadd.setBounds(70, 410, 220, 30);

        ephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ephoneActionPerformed(evt);
            }
        });
        jPanel1.add(ephone);
        ephone.setBounds(70, 340, 220, 30);

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Phone");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 320, 50, 16);

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("Mail");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, 90, 50, 16);

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        jPanel1.add(mail);
        mail.setBounds(450, 110, 220, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setText("Username");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 170, 90, 16);

        euser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euserActionPerformed(evt);
            }
        });
        jPanel1.add(euser);
        euser.setBounds(450, 190, 220, 30);

        epass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epassActionPerformed(evt);
            }
        });
        jPanel1.add(epass);
        epass.setBounds(450, 270, 220, 30);

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setText("Password");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 250, 90, 16);

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel11.setText("Position");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 320, 70, 16);

        epos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eposActionPerformed(evt);
            }
        });
        jPanel1.add(epos);
        epos.setBounds(450, 340, 220, 30);

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel12.setText("Salary");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(450, 390, 50, 16);

        esal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esalActionPerformed(evt);
            }
        });
        jPanel1.add(esal);
        esal.setBounds(450, 410, 220, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel13.setText("Employee Form");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(260, 10, 220, 41);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 490, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void ctzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctzActionPerformed

    private void egenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_egenderActionPerformed

    private void eaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eaddActionPerformed

    private void ephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ephoneActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void euserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_euserActionPerformed

    private void epassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epassActionPerformed

    private void eposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eposActionPerformed

    private void esalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//to add the employee
      try {
    String tname = ename.getText();
    String tcitizen = ctz.getText();
    String tgender = egender.getText();
    String tphone = ephone.getText();
    String taddress = eadd.getText();
    String tmail = mail.getText();
    String uname = euser.getText();
    String pass = epass.getText();
    String tposition = epos.getText();
    String tsalary = esal.getText();

    // Check if any of the text fields are empty
    if (tname.isEmpty() || tcitizen.isEmpty() || tgender.isEmpty() || tphone.isEmpty() || taddress.isEmpty() || tmail.isEmpty() || uname.isEmpty() || pass.isEmpty() || tposition.isEmpty() || tsalary.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
    } else {
        // All text fields are filled in, proceed with adding the employee to the database
        pst = conn.prepareStatement("insert into employee (name,citizen_no,gender,address,phone,mail,username,password,position,salary) values (?,?,?,?,?,?,?,?,?,?)");
        pst.setString(1, tname);
        pst.setString(2, tcitizen);
        pst.setString(3, tgender);
        pst.setString(4,taddress);
        pst.setString(5, tphone);
        pst.setString(6,tmail);
        pst.setString(7, uname);
        pst.setString(8, pass);
        pst.setString(9,tposition);
        pst.setString(10,tsalary);

        int k= pst.executeUpdate();
        if(k==1){
            JOptionPane.showMessageDialog(this, "Instructor Added Succesfully");
            ename.setText("");
            ctz.setText("");
            eadd.setText("");
            egender.setText("");
            ephone.setText("");
            mail.setText("");
            epos.setText("");
            euser.setText("");
            epass.setText("");
            esal.setText("");

            this.setVisible(false);
            Employee ins=new Employee();
            ins.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Failed to Add");

        }
    }
} catch (SQLException ex) {
    java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}

   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Employee m = new Employee();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
        

    // Add the code for updating the employee details here

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String id = null;
                new Addemployee(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ctz;
    private javax.swing.JTextField eadd;
    private javax.swing.JTextField egender;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField epass;
    private javax.swing.JTextField ephone;
    private javax.swing.JTextField epos;
    private javax.swing.JTextField esal;
    private javax.swing.JTextField euser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail;
    // End of variables declaration//GEN-END:variables
}
