    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BakeryManagementSystem;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xeetr
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
      setLocationRelativeTo(null);
        setResizable(false);
        connect();
        loadtable();
        
    }

    Connection conn;
    PreparedStatement pst;
    Statement st;
    
    public void connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/Bakerymanagementsystem", "root", "");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        editemployee = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Addemployee = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        deleteemployee = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        eemployee = new javax.swing.JLabel();
        inventory = new javax.swing.JLabel();
        order = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 219, 219));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setText("Employee");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 50, 190, 41);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jLabel17.setText("Edit Employee");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(510, 130, 160, 40);

        editemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Box.png"))); // NOI18N
        editemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(editemployee);
        editemployee.setBounds(470, 80, 230, 150);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel19.setText("Add Employee");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(270, 140, 170, 30);

        Addemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Box.png"))); // NOI18N
        Addemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(Addemployee);
        Addemployee.setBounds(240, 80, 230, 150);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jLabel21.setText("Delete Employee");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(740, 140, 180, 30);

        deleteemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Box.png"))); // NOI18N
        deleteemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(deleteemployee);
        deleteemployee.setBounds(710, 80, 230, 150);

        employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Citizen No", "Gender", "Address", "Phone", "Mail", "Position", "Salary"
            }
        ));
        employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employee);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 240, 680, 370);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 10, 130, 150);

        dashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N
        dashboard.setText("  Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel1.add(dashboard);
        dashboard.setBounds(40, 200, 150, 21);

        eemployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eemployee.setForeground(new java.awt.Color(255, 255, 255));
        eemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emplo.png"))); // NOI18N
        eemployee.setText("   Employee");
        eemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(eemployee);
        eemployee.setBounds(40, 250, 150, 25);

        inventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inventory.setForeground(new java.awt.Color(255, 255, 255));
        inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inebntory.png"))); // NOI18N
        inventory.setText("  Inventory");
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
        });
        jPanel1.add(inventory);
        inventory.setBounds(40, 300, 150, 25);

        order.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Order.png"))); // NOI18N
        order.setText("  Order");
        jPanel1.add(order);
        order.setBounds(40, 350, 150, 25);

        report.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Report.png"))); // NOI18N
        report.setText("  Report");
        jPanel1.add(report);
        report.setBounds(40, 400, 150, 25);

        setting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        setting.setForeground(new java.awt.Color(255, 255, 255));
        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setting.png"))); // NOI18N
        setting.setText("  Setting");
        jPanel1.add(setting);
        setting.setBounds(40, 450, 150, 25);

        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        logout.setText("  Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(40, 500, 150, 25);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/side.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 220, 620);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogooBakery.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(890, 0, 60, 64);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eemployeeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_eemployeeMouseClicked

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked
        // TODO add your handling code here:
        Inventory m = new Inventory();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_inventoryMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:

        Loginpanel m = new Loginpanel();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        Dashboard m = new Dashboard();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void deleteemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteemployeeMouseClicked
        // TODO add your handling code here:
        try {
        int row=employee.getSelectedRow();
         st = conn.createStatement();
         String cell = employee.getModel().getValueAt(row, 0).toString();
            System.out.println(cell);
          String query1 = "delete from  employee where id="+cell;
          
          st.executeUpdate(query1);
       } catch (SQLException excep) {
          excep.printStackTrace();
       } catch (Exception excep) {
          excep.printStackTrace();
       }
    JOptionPane.showMessageDialog(this, "Click Ok to Delete");

    this.setVisible(false);
    Employee ins = new Employee();
    ins.setVisible(true);
    }//GEN-LAST:event_deleteemployeeMouseClicked

    private void employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeMouseClicked

    private void editemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editemployeeMouseClicked
        // TODO add your handling code here:
            // Get the selected row index of the JTable
   int rowIndex = employee.getSelectedRow();
   if(rowIndex == -1) {
       // No row is selected, show an error message
       JOptionPane.showMessageDialog(null, "Please select a row to edit", "Error", JOptionPane.ERROR_MESSAGE);
       return;
   }

   // Get the values of the selected row from the JTable
   String empID = employee.getValueAt(rowIndex, 0).toString();
   String empName = employee.getValueAt(rowIndex, 1).toString();
   String empCitizenNo = employee.getValueAt(rowIndex, 2).toString();
   String empGender = employee.getValueAt(rowIndex, 3).toString();
   String empAddress = employee.getValueAt(rowIndex, 4).toString();
   String empPhone = employee.getValueAt(rowIndex, 5).toString();
   String empMail = employee.getValueAt(rowIndex, 6).toString();
   String empPosition = employee.getValueAt(rowIndex, 7).toString();
   String empSalary = employee.getValueAt(rowIndex, 8).toString();

   // Prompt the user to edit the information
   //empty textfield validation
   String newEmpName = JOptionPane.showInputDialog(null, "Enter the new name for employee " + empID, empName);
   if(newEmpName == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   String newEmpCitizenNo = JOptionPane.showInputDialog(null, "Enter the new citizen number for employee " + empID, empCitizenNo);
   if(newEmpCitizenNo == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   String newEmpGender = JOptionPane.showInputDialog(null, "Enter the new gender for employee " + empID, empGender);
   if(newEmpGender == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   String newEmpAddress = JOptionPane.showInputDialog(null, "Enter the new address for employee " + empID, empAddress);
   if(newEmpAddress == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   String newEmpPhone = JOptionPane.showInputDialog(null, "Enter the new phone number for employee " + empID, empPhone);
   if(newEmpPhone == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   String newEmpMail = JOptionPane.showInputDialog(null, "Enter the new email for employee " + empID, empMail);
   if(newEmpMail == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   String newEmpPosition = JOptionPane.showInputDialog(null, "Enter the new position for employee " + empID, empPosition);
   if(newEmpPosition == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   String newEmpSalary = JOptionPane.showInputDialog(null, "Enter the new salary for employee " + empID, empSalary);
   if(newEmpSalary == null) {
       // The user clicked the cancel button, do nothing
       return;
   }

   // Update the values of the selected row in the JTable
   employee.setValueAt(newEmpName, rowIndex, 1);
   employee.setValueAt(newEmpCitizenNo, rowIndex, 2);
   employee.setValueAt(newEmpGender, rowIndex, 3);
   employee.setValueAt(newEmpAddress, rowIndex, 4);
   employee.setValueAt(newEmpPhone, rowIndex, 5);
   employee.setValueAt(newEmpMail, rowIndex, 6);
   employee.setValueAt(newEmpPosition, rowIndex, 7);
   employee.setValueAt(newEmpSalary, rowIndex, 8);

   try {
       // Update the values of the selected row in the database
       PreparedStatement stmt = conn.prepareStatement("UPDATE employee SET name = ?, citizen_no = ?, gender = ?, address = ?, phone = ?, mail = ?, position = ?, salary = ? WHERE id = ?");
       stmt.setString(1, newEmpName);
       stmt.setString(2, newEmpCitizenNo);
       stmt.setString(3, newEmpGender);
       stmt.setString(4, newEmpAddress);
       stmt.setString(5, newEmpPhone);
       stmt.setString(6, newEmpMail);
       stmt.setString(7, newEmpPosition);
       stmt.setString(8, newEmpSalary);
       stmt.setString(9, empID);
       stmt.executeUpdate();
       JOptionPane.showMessageDialog(null, "Employee " + empID + " has been updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
   } catch (SQLException e) {
   JOptionPane.showMessageDialog(null, "Error updating employee " + empID + ": " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
   }

    }//GEN-LAST:event_editemployeeMouseClicked

    private void AddemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddemployeeMouseClicked
        String id = null;
        // TODO add your handling code here:
        Addemployee m = new Addemployee(id);

        m.setVisible(true);
    }//GEN-LAST:event_AddemployeeMouseClicked
 public void loadtable(){
          try {
            String query1="SELECT id, name,citizen_no,gender,address,phone,mail,position,salary FROM employee ";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query1);
            ResultSetMetaData rsmd =  (ResultSetMetaData) rs.getMetaData();
            DefaultTableModel model =(DefaultTableModel) employee.getModel();
            int cols= rsmd.getColumnCount();
            String[]colName =new String[cols];
            for(int i=0;i<cols;i++)
                colName[i]=rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            String id, name,citizen_no,gender,address,phone,mail,position,salary;
            while(rs.next()){
                id=rs.getString(1);
                name=rs.getString(2);
                citizen_no=rs.getString(3);
                gender=rs.getString(4);
                address=rs.getString(5);
                phone=rs.getString(6);
                mail=rs.getString(7);
                position=rs.getString(8);
                salary=rs.getString(9);


                String[] row ={id, name,citizen_no,gender,address,phone,mail,position,salary};
                model.addRow(row);
     }
       
    
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }
    public void Update(){
    


    
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addemployee;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel deleteemployee;
    private javax.swing.JLabel editemployee;
    private javax.swing.JLabel eemployee;
    private javax.swing.JTable employee;
    private javax.swing.JLabel inventory;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel order;
    private javax.swing.JLabel report;
    private javax.swing.JLabel setting;
    // End of variables declaration//GEN-END:variables
}
