/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BakeryManagementSystem;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xeetr
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
        connect();
        loadtable();
        setLocationRelativeTo(null);
        setResizable(false);
    }

       Connection conn;
    PreparedStatement pst;
    Statement st;
    public void connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/Bakerymanagementsystem", "root", "");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        eemployee = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Addemployee = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        editemployee = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        deleteemployee = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(220, 219, 219));
        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 20, 130, 140);

        dashboard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N
        dashboard.setText("  Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel1.add(dashboard);
        dashboard.setBounds(40, 200, 150, 21);

        eemployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        eemployee.setForeground(new java.awt.Color(255, 255, 255));
        eemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emplo.png"))); // NOI18N
        eemployee.setText("   Employee");
        eemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(eemployee);
        eemployee.setBounds(40, 250, 150, 23);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inebntory.png"))); // NOI18N
        jLabel11.setText("  Inventory");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 300, 150, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Order.png"))); // NOI18N
        jLabel8.setText("  Order");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 350, 150, 22);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Report.png"))); // NOI18N
        jLabel13.setText("  Report");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 400, 150, 22);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setting.png"))); // NOI18N
        jLabel14.setText("  Setting");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 450, 150, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        jLabel9.setText("  Logout");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 500, 150, 24);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/side.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 220, 620);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setText("Inventory");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 30, 190, 41);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jLabel19.setText("Add Item");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(290, 130, 120, 30);

        Addemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Box.png"))); // NOI18N
        Addemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(Addemployee);
        Addemployee.setBounds(240, 80, 230, 150);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jLabel17.setText("Edit Items");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(530, 130, 120, 40);

        editemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Box.png"))); // NOI18N
        editemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(editemployee);
        editemployee.setBounds(470, 80, 230, 150);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jLabel21.setText("Delete Items");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(750, 140, 130, 30);

        deleteemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Box.png"))); // NOI18N
        deleteemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteemployeeMouseClicked(evt);
            }
        });
        jPanel1.add(deleteemployee);
        deleteemployee.setBounds(700, 80, 230, 150);

        inventory.setBorder(new javax.swing.border.MatteBorder(null));
        inventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Catagory", "Price"
            }
        ));
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inventory);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 230, 680, 370);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogooBakery.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 0, 60, 64);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, -4, 940, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eemployeeMouseClicked
        // TODO add your handling code here:
        Employee m = new Employee();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_eemployeeMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        Inventory m = new Inventory();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Loginpanel m = new Loginpanel();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        Dashboard m = new Dashboard();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void AddemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddemployeeMouseClicked
        String id = null;
        // TODO add your handling code here:
        Additem m = new Additem();

        m.setVisible(true);
    }//GEN-LAST:event_AddemployeeMouseClicked

    private void deleteemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteemployeeMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        try {
        int row=inventory.getSelectedRow();
         st = conn.createStatement();
         String cell = inventory.getModel().getValueAt(row, 0).toString();
            System.out.println(cell);
          String query1 = "delete from  Inventory where id="+cell;
          
          st.executeUpdate(query1);
       } catch (SQLException excep) {
          excep.printStackTrace();
       } catch (Exception excep) {
          excep.printStackTrace();
       }
    JOptionPane.showMessageDialog(this, "Click Ok to Delete");

    this.setVisible(false);
    Inventory ins = new Inventory();
    ins.setVisible(true);
      
    }//GEN-LAST:event_deleteemployeeMouseClicked

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryMouseClicked

    private void editemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editemployeeMouseClicked
        // TODO add your handling code here:
        // Get the selected row index of the JTable
    int rowIndex = inventory.getSelectedRow();
    if (rowIndex == -1) {
        // No row is selected, show an error message
        JOptionPane.showMessageDialog(null, "Please select a row to edit", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get the values of the selected row from the JTable
    String itemId = inventory.getValueAt(rowIndex, 0).toString();
    String itemName = inventory.getValueAt(rowIndex, 1).toString();
    String itemquan = inventory.getValueAt(rowIndex, 2).toString();
    String itemCategory = inventory.getValueAt(rowIndex, 3).toString();
    String itemPrice = inventory.getValueAt(rowIndex, 4).toString();

    // Prompt the user to edit the information
    String newItemName = JOptionPane.showInputDialog(null, "Enter the new name for item " + itemId, itemName);
    if (newItemName == null) {
        // The user clicked the cancel button, do nothing
        return;
    }

    String newItemCategory = JOptionPane.showInputDialog(null, "Enter the new category for item " + itemId, itemCategory);
    if (newItemCategory == null) {
        // The user clicked the cancel button, do nothing
        return;
    }
    
     String newitemquan = JOptionPane.showInputDialog(null, "Enter the new quantity for item " + itemId, itemquan);
    if (newitemquan == null) {
        // The user clicked the cancel button, do nothing
        return;
    }

    String newItemPrice = JOptionPane.showInputDialog(null, "Enter the new price for product " + itemId, itemPrice);
    if (newItemPrice == null) {
        // The user clicked the cancel button, do nothing
        return;
    }

    // Update the values of the selected row in the JTable
    inventory.setValueAt(newItemName, rowIndex, 1);
    inventory.setValueAt(newitemquan, rowIndex, 2);
    inventory.setValueAt(newItemCategory, rowIndex, 3);
    inventory.setValueAt(newItemPrice, rowIndex, 4);

    try {
        // Update the values of the selected row in the database
        PreparedStatement stmt = conn.prepareStatement("UPDATE Inventory SET item_name = ?, quantity = ?, category = ?, unit_price = ? WHERE id = ?");
        stmt.setString(1, newItemName);
        stmt.setString(2, newitemquan);
        stmt.setString(3, newItemCategory);
        stmt.setString(4, newItemPrice);
        stmt.setString(5, itemId);
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Item " + itemId + " has been updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error updating item " + itemId + ": " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_editemployeeMouseClicked

     public void loadtable(){
          try {
            String query1="SELECT id, item_name, quantity ,category, unit_price FROM Inventory ";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query1);
            ResultSetMetaData rsmd =  (ResultSetMetaData) rs.getMetaData();
            DefaultTableModel model =(DefaultTableModel) inventory.getModel();
            int cols= rsmd.getColumnCount();
            String[]colName =new String[cols];
            for(int i=0;i<cols;i++)
                colName[i]=rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            String id, name,quantity,catagory,price;
            while(rs.next()){
                id=rs.getString(1);
                name=rs.getString(2);
                quantity=rs.getString(3);
                catagory=rs.getString(4);
                price=rs.getString(5);
                String[] row ={id, name, quantity, catagory,price};
                model.addRow(row);
     }
       
    
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }
    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addemployee;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel deleteemployee;
    private javax.swing.JLabel editemployee;
    private javax.swing.JLabel eemployee;
    private javax.swing.JTable inventory;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
