/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BakeryManagementSystem.Employee;

import BakeryManagementSystem.Addemployee;
import BakeryManagementSystem.Loginpanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.ResultSet;


/**
 *
 * @author Rohan Khatiwada
 */
public class Employeedashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        order = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalOrdersTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryStatus = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lowitems = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BOX3.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 219, 219));
        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 30, 130, 130);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dashboard.png"))); // NOI18N
        jLabel10.setText("  Dashboard");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 200, 150, 21);

        order.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Order.png"))); // NOI18N
        order.setText("  Order");
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });
        jPanel1.add(order);
        order.setBounds(40, 250, 150, 25);

        setting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        setting.setForeground(new java.awt.Color(255, 255, 255));
        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setting.png"))); // NOI18N
        setting.setText("  Setting");
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });
        jPanel1.add(setting);
        setting.setBounds(40, 300, 150, 25);

        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon.png"))); // NOI18N
        logout.setText("  Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(40, 550, 150, 25);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/side.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 220, 620);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel4.setText("Dashboard");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 10, 150, 41);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Total Orders");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(270, 80, 110, 25);

        totalOrdersTextField.setEditable(false);
        totalOrdersTextField.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalOrdersTextField.setText("yyy");
        totalOrdersTextField.setBorder(null);
        totalOrdersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalOrdersTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(totalOrdersTextField);
        totalOrdersTextField.setBounds(290, 110, 110, 50);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Inventory Items");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 220, 220, 41);

        inventoryStatus.setEditable(false);
        inventoryStatus.setBackground(new java.awt.Color(255, 255, 255));
        inventoryStatus.setColumns(1);
        inventoryStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        inventoryStatus.setLineWrap(true);
        inventoryStatus.setRows(10);
        inventoryStatus.setBorder(null);
        jScrollPane2.setViewportView(inventoryStatus);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(280, 250, 180, 270);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BOX2.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 210, 260, 360);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Low Inventory Items");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(550, 220, 220, 41);

        lowitems.setEditable(false);
        lowitems.setBackground(new java.awt.Color(255, 255, 255));
        lowitems.setColumns(1);
        lowitems.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lowitems.setForeground(new java.awt.Color(255, 51, 51));
        lowitems.setRows(10);
        lowitems.setBorder(null);
        lowitems.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(lowitems);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(550, 250, 180, 270);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BOX2.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 210, 260, 360);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Atotalorders.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 50, 230, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel10MouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        // TODO add your handling code here:
                TakeOrder m = new TakeOrder();
                this.hide();
                m.setVisible(true);
    }//GEN-LAST:event_orderMouseClicked

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        // TODO add your handling code here:
        Setting m = new Setting();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_settingMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        Loginpanel m = new Loginpanel();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void totalOrdersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalOrdersTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalOrdersTextFieldActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employeedashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employeedashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employeedashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employeedashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employeedashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inventoryStatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logout;
    private javax.swing.JTextArea lowitems;
    private javax.swing.JLabel order;
    private javax.swing.JLabel setting;
    private javax.swing.JTextField totalOrdersTextField;
    // End of variables declaration//GEN-END:variables
}
