/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employee;

import BakeryManagementSystem.Addemployee;
import BakeryManagementSystem.Dashboard;
import BakeryManagementSystem.Inventory;
import BakeryManagementSystem.Loginpanel;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;


/**
 *
 * @author Rohan Khatiwada
 */
public class TakeOrder extends javax.swing.JFrame {
    
    Boolean checkif=false;
    /**
     * Creates new form Order
     */
    public TakeOrder() {
        initComponents();
       connect();
//        loadtable();
        setLocationRelativeTo(null);
        setResizable(false);
    }

       Connection conn;
    PreparedStatement pst;
    Statement st;
    public void connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/Bakerymanagementsystem", "root", "");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pprice2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pname2 = new javax.swing.JTextField();
        pcat1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        pname3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pprice3 = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pprice4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        cat = new javax.swing.JTable();
        SpinnerNumberModel model = new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1);
        jSpinner1 = new javax.swing.JSpinner(model);
        pcat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 37, -1));

        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel14.setText("Payment Option");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 130, 16));

        fullname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 30));

        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel15.setText("Name");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 50, 16));

        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 220, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, 16));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(6, 6, 37, 0);

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("Category");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 50, 80, 16);

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Mobile Number");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 120, 130, 16);

        pprice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pprice2ActionPerformed(evt);
            }
        });
        jPanel2.add(pprice2);
        pprice2.setBounds(40, 140, 220, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Customers Details");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(40, 20, 150, 41);

        jLabel17.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel17.setText("Name");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(40, 60, 50, 16);

        pname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pname2ActionPerformed(evt);
            }
        });
        jPanel2.add(pname2);
        pname2.setBounds(40, 80, 220, 30);

        pcat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cake", "Cookies", "Drinks", "Others" }));
        jPanel2.add(pcat1);
        pcat1.setBounds(340, 70, 220, 30);

        jLabel18.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel18.setText("Name");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(620, 50, 50, 16);

        pname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pname3ActionPerformed(evt);
            }
        });
        jPanel2.add(pname3);
        pname3.setBounds(620, 70, 220, 30);

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("Mobile Number");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(620, 110, 130, 16);

        pprice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pprice3ActionPerformed(evt);
            }
        });
        jPanel2.add(pprice3);
        pprice3.setBounds(620, 130, 220, 30);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        price.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 220, 30));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setText("Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 130, 16));

        pprice4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pprice4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pprice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pprice4ActionPerformed(evt);
            }
        });
        jPanel1.add(pprice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 220, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 110, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 480, 310));

        cat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        cat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 310));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSpinner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 220, 30));

        pcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cake", "Cookies", "Drinks", "Others" }));
        pcat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcatMouseClicked(evt);
            }
        });
        pcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcatActionPerformed(evt);
            }
        });
        jPanel1.add(pcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Catagory");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 16));

        b.setEditable(false);
        b.setColumns(5);
        b.setRows(5);
        jScrollPane3.setViewportView(b);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 400, 350));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 130, -1));

        jLabel20.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel20.setText("Price in Rs.");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 80, 16));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel19.setText("Customer Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 16));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Method", "Cash", "Online"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 472, 150, 30));

        jButton6.setText("Pay");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(name.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error  ");

        }
        else{
            addtables(name.getText(),Integer.parseInt(price.getText()), (int)jSpinner1.getValue(), pprice4.getText());
        showBill();
        
        }
        clearButton();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcatActionPerformed
        String value = pcat.getSelectedItem().toString();
        if(value=="Cake"){
            loadtable("Cake");
            showBill();

            //
        }
        else if( value=="Cookies"){
            loadtable("Cookies");
            showBill();

        }        
    }//GEN-LAST:event_pcatActionPerformed

    private void pcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pcatMouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        priceCalculator();        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    private void catMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catMouseClicked
        // TODO add your handling code here:
        int selectedRow = cat.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)cat.getModel();
        name.setText(model.getValueAt(selectedRow, 0).toString());
        price.setText(model.getValueAt(selectedRow, 1).toString());
        jSpinner1.setValue(1);

    }//GEN-LAST:event_catMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearButton();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        if(!checkif){
                        JOptionPane.showMessageDialog(null, "Make payment first");
        }
        else{
       saveOrder();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pprice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pprice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pprice4ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void pprice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pprice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pprice3ActionPerformed

    private void pname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pname3ActionPerformed

    private void pname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pname2ActionPerformed

    private void pprice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pprice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pprice2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        showBill();        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Employeedashboard edb = new Employeedashboard();
        this.setVisible(false);
        edb.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         if(b.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please order first!!");
        }
        else if(jComboBox1.getSelectedItem().equals("Select Method")){
            JOptionPane.showMessageDialog(null, "Please select the payment method");
        }
                else if(jComboBox1.getSelectedItem().equals("Cash")){
            JOptionPane.showMessageDialog(null, "Please reveive the Cash!!");
        }
        else if (jComboBox1.getSelectedItem().equals("Online")){
//               Scan and payment
            try{
                File file1 = new File("public\\online.png");
//                String data = String.format(String.valueOf((char) cal()));
                String data = String.format(totalAmo());

                ByteArrayOutputStream out = QRCode.from(data).withSize(250, 250).to(ImageType.PNG).stream();
                FileOutputStream fos = new FileOutputStream(file1);
                out.writeTo(fos);
                out.flush();
                fos.close();

            }
            catch(Exception e){
                System.out.println(e);

            }
            JFrame newframe=new JFrame();
            newframe.setBounds(700,200,350,200);
            newframe.setResizable(false);
            newframe.setLayout(null);

            JButton button = new JButton("Esewa");
            button.setForeground(Color.WHITE);
            button.setBackground(Color.blue);
            button.setFocusable(false);
            button.setCursor(new Cursor(Cursor. HAND_CURSOR));
            button.setBounds(70, 50, 100, 25);
            newframe.add(button);

            JLabel label = new JLabel();
            label.setBounds(40, 90, 500, 50);
            label.setFont(label.getFont().deriveFont(17f));
            label.setForeground(Color.red);
            newframe.add(label);

            JButton button1 = new JButton("Scan");
            button1.setForeground(Color.WHITE);
            button1.setBackground(Color.blue);
            button1.setFocusable(false);
            button1.setCursor(new Cursor(Cursor. HAND_CURSOR));
            button1.setBounds(180, 50, 100, 25);
            button1.setBorder(BorderFactory.createRaisedBevelBorder());
            newframe.add(button1);

            button1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    newframe.dispose();
                    label.setText("");
                    JFrame scanner=new JFrame();
                    scanner.setBounds(700,200,403,403);
                    scanner.setResizable(false);
                    scanner.setLayout(null);
                    JLabel admin_pic_label = new JLabel(new ImageIcon("public\\online.png"));
                    admin_pic_label.setBounds(0,0,400,400);
                    scanner.add(admin_pic_label);
                    scanner.setVisible(true);
                            checkif=true;

                }});
            button.addActionListener((new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    label.setText("Esewa is currently not available");
                    button.setEnabled(false);
                }}));
            newframe.setVisible(true);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    public void loadtable(String product){
          try {
            String query1="SELECT item_name, unit_price FROM Inventory where category = ? ";
                  PreparedStatement pstmt = conn.prepareStatement(query1);
                  pstmt.setString(1, product);
                  ResultSet rs = pstmt.executeQuery();
        // Create a new data model with the selected items
   ArrayList<String[]> items = new ArrayList<>();
        while (rs.next()) {
            String[] item = {rs.getString("item_name"), rs.getString("unit_price")};
            items.add(item);
        }
        Object[][] data = new Object[items.size()][2];
        for (int i = 0; i < items.size(); i++) {
            data[i][0] = items.get(i)[0];
            data[i][1] = items.get(i)[1];
        }
        String[] columnNames = {"item_name", "unit_price"};
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        cat.setModel(model);
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }

void priceCalculator(){
    int quantity=(int)jSpinner1.getValue();
    int pricefinal=Integer.parseInt(price.getText());
    String total=String.valueOf(quantity * pricefinal );
    pprice4.setText(total);
//    showBill();

}



void clearButton(){
    price.setText(String.valueOf(0));
    jSpinner1.setValue(0);
    pprice4.setText("");
    name.setText("");
    
}

void clearAll(){
    clearButton();
        b.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
}

public void addtables(String Name, int price, int Qty ,String Total){
    DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
    DecimalFormat df = new DecimalFormat("00.00") ;
    double totPrice = price * Double.valueOf(Qty) ;
    String TotalPrice = df.format(totPrice);

    // Update Inventory table with reduced quantity
    try {
        String query1="SELECT quantity FROM Inventory where item_name = ?";
        PreparedStatement pstmt = conn.prepareStatement(query1);
        pstmt.setString(1, Name);
        ResultSet rs = pstmt.executeQuery();
        int currentQty = 0;
        if (rs.next()) {
            currentQty = rs.getInt("quantity");
        }
        int newQty = currentQty - Qty;
        if (newQty < 0) {
            JOptionPane.showMessageDialog(this, "Not enough stock for "+Name);
            return;
        }
        String query2 = "UPDATE Inventory SET quantity=? WHERE item_name=?";
        PreparedStatement pstmt2 = conn.prepareStatement(query2);
        pstmt2.setInt(1, newQty);
        pstmt2.setString(2, Name);
        pstmt2.executeUpdate();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }

    // Add order details to the table
    Vector v = new Vector();
    v.add(Name);
    v.add(price);
    v.add(Qty);
    v.add(TotalPrice);
    dt.addRow(v);
}


public String totalAmo(){
            float sum=0;
        for(int i=0;i<jTable1.getRowCount();i++){

            sum=sum+ Float.parseFloat((jTable1.getValueAt(i,3).toString()));
        }
        return String.valueOf(sum);
}

     public float cal(){
        //cal total table values
        float sum=0;
        for(int i=0;i<jTable1.getRowCount();i++){

            sum=sum+ Float.parseFloat((jTable1.getValueAt(i,3).toString()));
        }
        return sum;

    }
     
     
//     to add the quantity if the product
    public String AddQty(){
         int sum=0;
        for(int i=0;i<jTable1.getRowCount();i++){
            sum=sum+ Integer.parseInt((jTable1.getValueAt(i,2).toString()));
        }
        return String.valueOf(sum);
         
     }
    /// The following code saves the order data in orders table and saves the total orders
    void saveOrder(){
    try {
        String cusName = fullname.getText();
        String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        
        // Check if any of the text fields are empty
        if (cusName.isEmpty()) { // check if the customer name is null
            JOptionPane.showMessageDialog(this, "Customer name is empty!!");
        } 
        else if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please make some order first!!");
        }
        else {
            // All text fields are filled in, proceed with adding the order to the database
            pst = conn.prepareStatement("INSERT INTO orders (customerName, quantity, Date, Total) VALUES (?, ?, ?, ?)");
            pst.setString(1, cusName);
            pst.setString(2, AddQty());
            pst.setString(3, date);
            pst.setFloat(4, cal());

            int k = pst.executeUpdate();
            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Order added successfully");
                PrintBill();

                // Calculate and update the total orders for today in the OrderStatistics table
                PreparedStatement ps = conn.prepareStatement("UPDATE OrderStatistics SET Total_orders = Total_orders + 1 WHERE Date = ?");
                ps.setString(1, date);
                int rowsUpdated = ps.executeUpdate();
                
                // If no rows were updated, it means there were no previous entries for today's date
                // In that case, insert a new row for today's date in the OrderStatistics table
                if (rowsUpdated == 0) {
                    PreparedStatement psInsert = conn.prepareStatement("INSERT INTO OrderStatistics (Date, Total_orders) VALUES (?, ?)");
                    psInsert.setString(1, date);
                    psInsert.setInt(2, 1);
                    psInsert.executeUpdate();
                }
            } 
            else {
                JOptionPane.showMessageDialog(this, "Failed to add product");
            }
        }
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
}

     
     
     
     void PrintBill(){
                 if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Please Select the food first !!");
        }else {try {
            showBill();
            boolean print = b.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Unable To Print !!..");
            }} catch (PrinterException ex) {
                                JOptionPane.showMessageDialog(this, "Failed to print bill ");

            JOptionPane.showMessageDialog(null, ex.getMessage());
        }} 
     }


void showBill(){
//        if (jTable1.getRowCount() == 0) {
//            JOptionPane.showMessageDialog(null, "Please make order first!!");
//        } else {
            try {

                b.setText("                                               Mitho Bakery \n");
                b.setText(b.getText() + "                                                    Naxal \n");
                b.setText(b.getText() + "                                            Kathmandu,Nepal \n");
                b.setText(b.getText() + "                                          +977 ########, \n");
                b.setText(b.getText() + "-----------------------------------------------------------------------------------------------\n");
                b.setText(b.getText() + "Customer name:              "+ fullname.getText()+"\n");
                b.setText(b.getText() + "-----------------------------------------------------------------------------------------------\n");
                b.setText(b.getText() + "  Item\t\tQty\tPrice \tTotal" +"\n");
                b.setText(b.getText() + "-----------------------------------------------------------------------------------------------\n");

                DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
                // get table Product details
                for (int i = 0; i < jTable1.getRowCount(); i++) {

                    String Name = df.getValueAt(i, 0).toString();
                    String Qty = df.getValueAt(i, 2).toString();
                    String Price = df.getValueAt(i, 1).toString();
                    String Total = df.getValueAt(i, 3).toString();


                    b.setText(b.getText() +"  "+ Name+"\t\t"+Qty +"\t"+Price + "\t"+Total +"\n");
                }

                b.setText(b.getText() + "----------------------------------------------------------------------------------------------\n");
                b.setText(b.getText() + "Total :                                                                                     " + cal() +"\n");
                b.setText(b.getText() + "----------------------------------------------------------------------------------------------\n");
                b.setText(b.getText() + "                                    Thanks For Your Order...!"+"\n");
                b.setText(b.getText() + "----------------------------------------------------------------------------------------------\n");
                b.setText(b.getText() + "                                      Visit Again with Smile"+"\n");

            } catch (Exception e) {
            }
//        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea b;
    private javax.swing.JTable cat;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> pcat;
    private javax.swing.JComboBox<String> pcat1;
    private javax.swing.JTextField pname2;
    private javax.swing.JTextField pname3;
    private javax.swing.JTextField pprice2;
    private javax.swing.JTextField pprice3;
    private javax.swing.JTextField pprice4;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
